 languageCode = "uk"
 languageName = "Українська"
 displayName = "УКР"
 isoCode = "uk"
 weight = 2

 title = "Андрій Сербовець"
 description = "Перекладаю, редагую, локалізую усяку всячину"
 copyright = "© Сербовець А. А."

 dateFormat = "2 January 2006"
 
[params]  
 # mainSections = ["section1", "section2"]

[params.author]
  name = "Андрій Сербовець"
  image = "img/author.jpg"
  headline = "Перекладаю, редагую, локалізую усяку всячину"
  bio = "А тут трохи про себе"

links = [
  #   { email = "mailto:hello@your_domain.com" },
  #   { link = "https://link-to-some-website.com/" }, },
  #   { codepen = "https://codepen.io/username" },
  #   { discord = "https://discord.gg/invitecode" },
  { github = "https://github.com/archdron" },
  { linkedin = "https://linkedin.com/in/aserbovets" },
  { mastodon = "https://mastodon.online/@archdron" },
  { medium = "https://medium.com/@archdron" },
  { telegram = "https://t.me/aserbovets" },
  ]
