languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1

title = "Andrii Serbovets"
description = "Translating, editing, localizing games and stuff"
copyright = "© Andrii Serbovets"
dateFormat = "Jan 2, 2006"

[params]
  #mainSections = ["section1", "section2"]

[params.author]
  name = "Andrii Serbovets"
  image = "img/author.jpg"
  headline = "Translating, editing, proofreading, and localizing stuff"
  bio = "A little bit about you"
  links = [
  #   { email = "mailto:hello@your_domain.com" },
  #   { link = "https://link-to-some-website.com/" }, },
  #   { codepen = "https://codepen.io/username" },
  #   { discord = "https://discord.gg/invitecode" },
  { github = "https://github.com/archdron" },
  { linkedin = "https://linkedin.com/in/aserbovets" },
  { mastodon = "https://mastodon.online/@archdron" },
  { medium = "https://medium.com/@archdron" },
  { telegram = "https://t.me/aserbovets" },
  ]